<?xml version='1.0'?>

<robot name="mower_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find mower_bot)/urdf/mower_bot.gazebo" />

  <!-- Length along X-axis, Width along Y-axis, Height along Z-axis -->
  <xacro:property name="mower_width" value="0.4" />
  <xacro:property name="mower_length" value="0.46" />
  <xacro:property name="mower_height" value="0.3" />
  <xacro:property name="mower_mass" value="8" />

  <xacro:property name="base_x_offset" value="0" />

  <xacro:property name="mower_inertia" value="${mower_mass/10.0}" />
  <xacro:property name="mower_i_x_pos" value="${wheel_x_offset + mower_length/3.0}" />
  <xacro:property name="mower_i_z_pos" value="${mower_height/10.0}" />

  <xacro:property name="mower_frame_width" value="${mower_width - 2.1 * wheel_length}" />
  <xacro:property name="mower_frame_length" value="${mower_length*1.2}" />
  <xacro:property name="mower_frame_height" value="${mower_height/4.0}" />

  <xacro:property name="hardware_width" value="${mower_width/2.0}" />
  <xacro:property name="hardware_length" value="${mower_length/2.0}" />
  <xacro:property name="hardware_height" value="${mower_height/2.0}" />
  <xacro:property name="hardware_z_offset" value="${hardware_height/2.0}" />

  <xacro:property name="wheel_length" value="0.05" />
  <xacro:property name="wheel_radius" value="0.08" />
  <xacro:property name="wheel_mass" value="1" />
  <xacro:property name="wheel_inertia" value="1e-3" />
  <xacro:property name="wheel_x_offset" value="${base_x_offset - mower_length/2.0}" />
  <xacro:property name="wheel_y_offset" value="${mower_width/2.0 - wheel_length/2.0}" />

  <xacro:property name="caster_radius" value="${wheel_radius/2.0}" />
  <xacro:property name="caster_x_offset" value="${base_x_offset + mower_length/2.0}" />
  <xacro:property name="caster_y_offset" value="${wheel_y_offset - 0.07}" />
  <xacro:property name="caster_z_offset" value="${caster_radius}" />

  <xacro:property name="camerra_width" value="0.05" />
  <xacro:property name="camerra_length" value="0.05" />
  <xacro:property name="camerra_height" value="0.05" />
  <xacro:property name="camerra_x_offset" value="${hardware_length/2.0 + base_x_offset - camerra_length/2.0 + 0.001}" />
  <xacro:property name="camerra_z_offset" value="${hardware_height - camerra_height/2.0 + 0.001}" />

  <xacro:property name="laser_width" value="0.1" />
  <xacro:property name="laser_length" value="0.1" />
  <xacro:property name="laser_height" value="0.1" />
  <xacro:property name="laser_x_offset" value="${base_x_offset}" />
  <xacro:property name="laser_z_offset" value="${hardware_height + 0.025}" />


  <link name="robot_footprint"></link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint" />
    <child link="chassis" />
  </joint>

  <link name='chassis'>
    <inertial>
      <mass value="${mower_mass}"/>
      <origin xyz="${mower_i_x_pos} 0 ${mower_i_z_pos}" rpy=" 0 0 0"/>
      <inertia
          ixx="${mower_inertia}" ixy="0" ixz="0"
          iyy="${mower_inertia}" iyz="0"
          izz="${mower_inertia}" />
    </inertial>

    <collision>
      <origin xyz="${base_x_offset} 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${mower_frame_length} ${mower_frame_width} ${mower_frame_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${base_x_offset} 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${mower_frame_length} ${mower_frame_width} ${mower_frame_height}"/>
      </geometry>
    </visual>

    <!-- blade frame -->
    <collision>
      <origin xyz="${base_x_offset} 0 0" rpy=" 0 0 0"/>
      <geometry>
        <cylinder radius="${mower_width/2.0}" length="${mower_frame_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${base_x_offset} 0 0" rpy=" 0 0 0"/>
      <geometry>
        <cylinder radius="${mower_width/2.0}" length="${mower_frame_height}"/>
      </geometry>
    </visual>

    <!-- hardware frame -->
    <collision>
      <origin xyz="${base_x_offset} 0 ${hardware_z_offset}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${hardware_length} ${hardware_width} ${hardware_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${base_x_offset} 0 ${hardware_z_offset}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${hardware_length} ${hardware_width} ${hardware_height}"/>
      </geometry>
    </visual>

    <collision name='left_caster_collision'>
      <origin xyz="${caster_x_offset} ${caster_y_offset} -${caster_z_offset}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <visual name='left_caster_visual'>
      <origin xyz="${caster_x_offset} ${caster_y_offset} -${caster_z_offset}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </visual>

    <collision name='right_caster_collision'>
      <origin xyz="${caster_x_offset} -${caster_y_offset} -${caster_z_offset}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <visual name='right_caster_visual'>
      <origin xyz="${caster_x_offset} -${caster_y_offset} -${caster_z_offset}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </visual>

  </link>


  <!-- left wheel -->
  <joint type="continuous" name="left_wheel_hinge">
    <origin xyz="${wheel_x_offset} ${wheel_y_offset} 0" rpy="0 0 0"/>
    <child link="left_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <link name="left_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
      <inertia
        ixx="${wheel_inertia}" ixy="0" ixz="0"
        iyy="${wheel_inertia}" iyz="0"
        izz="${wheel_inertia}" />
    </inertial>
    <collision name="left_wheel_collision">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>100</mu>
            <mu2>100</mu2>
            <slip1>0</slip1>
            <slip2>0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <visual name="left_wheel_visual">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>


  <!-- right wheel -->
  <joint type="continuous" name="right_wheel_hinge">
    <origin xyz="${wheel_x_offset} -${wheel_y_offset} 0" rpy="0 0 0"/>
    <child link="right_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

  <link name="right_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
      <inertia
          ixx="${wheel_inertia}" ixy="0" ixz="0"
          iyy="${wheel_inertia}" iyz="0"
          izz="${wheel_inertia}" />
    </inertial>
    <collision name="right_wheel_collision">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>100</mu>
            <mu2>100</mu2>
            <slip1>0</slip1>
            <slip2>0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <visual name="right_wheel_visual">
      <origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>


  <link name='camera'>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6"/>
    </inertial>
    <collision name='camera_collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${camerra_length} ${camerra_width} ${camerra_height}"/>
      </geometry>
    </collision>
    <visual name='camera_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${camerra_length} ${camerra_width} ${camerra_height}"/>
      </geometry>
    </visual>
  </link>

  <joint type="fixed" name="camera_joint">
    <origin xyz="${camerra_x_offset} 0 ${camerra_z_offset}" rpy="0 0 0"/>
    <child link="camera"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>


  <link name='hokuyo'>
    <pose>0 0 0 0 0 0</pose>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6" />
    </inertial>
    <collision name='hokuyo_collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${laser_length} ${laser_width} ${laser_height}"/>
      </geometry>
    </collision>
    <visual name='hokuyo_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <mesh filename="package://mower_bot/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
  </link>

  <joint type="fixed" name="hokuyo_joint">
    <origin xyz="${laser_x_offset} 0 ${laser_z_offset}" rpy="0 0 0"/>
    <child link="hokuyo"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
  </joint>

</robot>
